on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "**"
  pull_request:

name: CI
jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.1
        with:
          version: 7.1.5
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm prepare
      - run: pnpm turbo run build --filter="./packages/**" build
      - run: pnpm lint
      - run: pnpm check

  Tests:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - run: git config --global core.autocrlf false
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.1
        with:
          version: 7.1.5
      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm build
