on:
  push:
    tags:
      - "stfc-space-user-storage@**"
    branches:
      - "next"

name: stfc.space-user-storage - Deploy

jobs:
  consecutiveness:
    runs-on: ubuntu-latest
    permissions:
      actions: read
    steps:
      - uses: mktcode/consecutive-workflow-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    # prevents this action from running on forks
    if: github.repository == 'stfc-space/frontend'
    name: Deploy stfc.space-user-storage
    runs-on: ubuntu-latest
    env:
      JWT_SECRET: ${{ secrets.DEV_JWT_SECRET }}
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
      SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
      CF_WORKERS: "1"

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 18.x
          cache: pnpm

      - name: Set env
        run: echo "TARGET_ENV=$(./.github/workflows/detect_target_env.sh)" >> $GITHUB_ENV

      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 7.1.5

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm turbo run --filter "stfc-space-user-storage" build

      - name: Deploy
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN_STFC_SPACE }}
          workingDirectory: "services/stfc.space-user-storage"
          environment: ${{ env.TARGET_ENV }}
