name: Release

on:
  push:
    branches-ignore:
      - "changeset**"
    tags-ignore:
      - "**"

jobs:
  release:
    # prevents this action from running on forks
    if: github.repository == 'stfc-space/frontend'
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0
          ssh-key: ${{ secrets.COMMIT_KEY }}

      - uses: pnpm/action-setup@v2.2.1
        with:
          version: 7.1.5
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: pnpm

      - run: pnpm install --frozen-lockfile

      - name: Setup Git User
        run: |
          git config user.name "radion-actions[bot]"
          git config user.email "radion-actions[bot]@stfc.space"

      - name: Create Release Pull Request
        id: changesets
        uses: changesets/action@v1
        with:
          createGithubReleases: false
          setupGitUser: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish
        if: steps.changesets.outputs.hasChangesets == 'false'
        run: pnpm release

      # We have to do this because if we use git push --follow-tags GitHub will ignore
      # the tags partially if we push multiple at once and thus not trigger workflows
      # pushing them individually works fine, so here we are
      - name: Push Tags
        run: |
          rm $HOME/.netrc
          node scripts/pushTagsToPush.js

      # TODO alert discord
      # - name: Send a Slack notification if a publish happens
      #   if: steps.changesets.outputs.published == 'true'
      #   # You can do something when a publish happens.
      #   run: my-slack-bot send-notification --message "A new version of ${GITHUB_REPOSITORY} was published!"
